// File generated by Antigravity (manual fallback for flutterfire configure)
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvxl7qstnVwvt2IU1G6s-Nz4URhwhx410',
    appId: '1:318186059918:android:a7f67a6333c810c5b931df',
    messagingSenderId: '318186059918',
    projectId: 'electropoint-8c3d1',
    storageBucket: 'electropoint-8c3d1.firebasestorage.app',
    databaseURL: 'https://electropoint-8c3d1-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2pZulC12myNzAFFU23hjekdWVUeUq8yc',
    appId: '1:318186059918:ios:a8e52afd3ddcdf11b931df',
    messagingSenderId: '318186059918',
    projectId: 'electropoint-8c3d1',
    storageBucket: 'electropoint-8c3d1.firebasestorage.app',
    iosBundleId: 'bo.e2v.electropoint',
    iosClientId: '318186059918-tef03r3jbh5f4bk4vbboi6c97pi4vt34.apps.googleusercontent.com',
    databaseURL: 'https://electropoint-8c3d1-default-rtdb.firebaseio.com',
  );
}
